# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('destination_city', models.CharField(max_length=150)),
                ('destination_country', models.CharField(max_length=150)),
                ('arrival_date', models.DateTimeField()),
                ('departure_date', models.DateTimeField()),
            ],
        ),
    ]
