# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Traveller',
            fields=[
                ('traveller_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('nationality', models.CharField(max_length=30)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=30)),
                ('preferences', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('travel_plan_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('tavel_plan_name', models.CharField(max_length=200)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('location_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogo.Location')),
                ('traveller_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogo.Traveller')),
            ],
        ),
    ]
