# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 09:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gogo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='travelplan',
            old_name='tavel_plan_name',
            new_name='travel_plan_name',
        ),
    ]
